# Generated by Django 3.1.7 on 2021-04-20 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prover.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('availability_flag', models.BooleanField(default=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prover.directory')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('availability_flag', models.BooleanField(default=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prover.directory')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(prover.models.SectionCategory.SectionCategoryEnum['PROCEDURE'], 'procedure'), (prover.models.SectionCategory.SectionCategoryEnum['PROPERTY'], 'property'), (prover.models.SectionCategory.SectionCategoryEnum['LEMMA'], 'lemma'), (prover.models.SectionCategory.SectionCategoryEnum['ASSERTION'], 'assertion'), (prover.models.SectionCategory.SectionCategoryEnum['INVARIANT'], 'invariant'), (prover.models.SectionCategory.SectionCategoryEnum['PRECONDITION'], 'precondition'), (prover.models.SectionCategory.SectionCategoryEnum['POSTCONDITION'], 'postcondition')], max_length=256)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(prover.models.SectionStatus.SectionStatusEnum['PROVED'], 'proved'), (prover.models.SectionStatus.SectionStatusEnum['INVALID'], 'invalid'), (prover.models.SectionStatus.SectionStatusEnum['COUNTEREXAMPLE'], 'counterexample'), (prover.models.SectionStatus.SectionStatusEnum['UNCHECKED'], 'unchecked')], max_length=256)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prover.sectionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prover.sectioncategory')),
                ('file', models.ForeignKey(help_text='File, to which section relates.', on_delete=django.db.models.deletion.CASCADE, to='prover.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prover.filesection')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prover.sectionstatus')),
            ],
        ),
    ]
